# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "Fast, open-source database migration tool with undo, dry-run, diff, and linting"
  homepage "https://github.com/frankchan/drift"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.2.0/drift_darwin_amd64.tar.gz"
      sha256 "6777e1fbeb6c9eca7bdd34eeecb2fddba22a50d44ffd5093df138f1e956659ac"

      def install
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.2.0/drift_darwin_arm64.tar.gz"
      sha256 "c73f12cfedf88408302e32354d86418f91ceb1b8644fbe9c13182ecdc2d0c5cd"

      def install
        bin.install "drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.2.0/drift_linux_amd64.tar.gz"
      sha256 "9d2d1dc9a11f6bd25e0c194a072c33d0ee98eb7f21e834938105ac074be364b7"
      def install
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.2.0/drift_linux_arm64.tar.gz"
      sha256 "eb78a812f6b07462e5059c262d611b5c2d3b9ef3237ead666eda9be7f3ba7735"
      def install
        bin.install "drift"
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
