# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "Fast, open-source database migration tool with undo, dry-run, diff, and linting"
  homepage "https://github.com/frankchan/drift"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.1.1/drift_darwin_amd64.tar.gz"
      sha256 "62b077fc3e8b1e565ec6b913eac04bc309a942ea27e09328ec4fbfa2827fd1cc"

      def install
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.1.1/drift_darwin_arm64.tar.gz"
      sha256 "2d450e497ab71b2cc682c2b44f0d9450d4f7820a97be01b46e877f63d39a9521"

      def install
        bin.install "drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.1.1/drift_linux_amd64.tar.gz"
      sha256 "b06b007455508ecbfe793636d8ca1d36892dea358d2788185d8867408bcff387"
      def install
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dunkinfrunkin/drift/releases/download/v0.1.1/drift_linux_arm64.tar.gz"
      sha256 "7a5f8abd87610af814b3b9c2a9613af98bb5737f57acc8157ba3867799729130"
      def install
        bin.install "drift"
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
